services:
  signaling-server:
    build: .
    container_name: signaling-server
    labels:
      - traefik.enable=true
      - traefik.http.routers.airbrawl-signaling-https.rule=(Host(`airbrawl-signaling.titaye.dev`))
      - traefik.http.routers.airbrawl-signaling-https.tls=true
      - traefik.http.routers.airbrawl-signaling-https.tls.certresolver=myresolver
      - traefik.http.routers.airbrawl-signaling.rule=(Host(`airbrawl-signaling.titaye.dev`))

    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true