services:
  signaling-server:
    build: .
    container_name: signaling-server
    labels:
      - traefik.enable=true
      - traefik.http.routers.air-brawl-https.rule=(Host(`air-brawl.titaye.dev`))
      - traefik.http.routers.air-brawl-https.tls=true
      - traefik.http.routers.air-brawl-https.tls.certresolver=myresolver
      - traefik.http.routers.air-brawl.rule=(Host(`air-brawl.titaye.dev`))

    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true