name: ⚗️ Tests

on:
  push:

jobs:
  perform-tests:
    name: ⚗️ Perform tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Build
        run: dotnet build

      - name: Perform tests
        run: dotnet run --no-build --project src/SignalingServer.Tests --fail-on-focused-tests --junit-summary TestResults.xml

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: src/SignalingServer.Tests/TestResults.xml
        if: ${{ always() }}

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: src/SignalingServer.Tests/TestResults.xml
        if: always()
